In [6]:
import pandas as pd

In [9]:
import pandas as pd
file_path = 'data\custom_data\MSATTS_V2_normalisé.csv'
df = pd.read_csv(file_path)
display(df)

,Nom du fichier,Texte corrigé
0,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,مَاذَا تَخْفِيَانِ عَنِّي؟
1,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,لا شَيْءَ يَا اُمِّي
2,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,نَبْرَهَ كَلاَمِكَ لاَ تُرِيحُنِي
3,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,اِنَّهُ سِرٌّ بَينَنا وَبَينَ جَدِّنا القادِرْ
4,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,سِرٌّ عَلَي اُمِّكَ يَا صَفَاءُ؟
...,...,...
1550,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,فَاَنَا لاَ اَحْتَمِلُ حَرَارَهَ هَذِهِ الشَّم...
1551,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,نَحْنُ مُجَرَّدُ عَبِيدٍ مِن
1552,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,مِثْلُ حَصَي الرِّمَالِ
1553,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,يَدُوسُونَ عَلَيْهَا فَقَطْ
1554,/content/drive/MyDrive/PFE_IA_TTS_Finale/Colle...,فَمِنْ اَجْلِ مَنْ تَتَحَمَّلُ الاَلَمَ؟

In [14]:
%pip install google-colab

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement google-colab (from versions: none)
ERROR: No matching distribution found for google-colab

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Charger le fichier CSV
file_path = 'data\custom_data\MSATTS_updated.csv'
df = pd.read_csv(file_path)


# Diviser le dataset en train et validation
train_df, val_df = train_test_split(df, train_size=0.8, shuffle=True, random_state=42)
# Chemins de sortie pour les fichiers texte
train_file = 'data\custom_data/train.txt'
val_file = 'data\custom_data/validation.txt'

# Fonction pour écrire les données dans un fichier texte
def write_to_file(df, output_file):
    with open(output_file, 'w', encoding='utf-8') as f:
        for index, row in df.iterrows():
            # Format : "Nom du fichier|Texte diacrité|Speaker_ID"
            line = f"{row['Nom du fichier']}|{row['Texte diacrité']}|{row['Speaker_ID']}\n"
            f.write(line)

# Écrire les fichiers train.txt et validation.txt
write_to_file(train_df, train_file)
write_to_file(val_df, val_file)

# Confirmer la création des fichiers
print(f"Fichier d'entraînement créé : {train_file} ({len(train_df)} lignes)")
print(f"Fichier de validation créé : {val_file} ({len(val_df)} lignes)")

Fichier d'entraînement créé : data\custom_data/train.txt (1702 lignes)
Fichier de validation créé : data\custom_data/validation.txt (426 lignes)

In [3]:
# Opening training and validation datasets

with open('data\custom_data/train.txt', 'r', encoding='utf-8') as file: # Changed encoding to 'utf-8'
  train_data = file.readlines()

with open('data\custom_data/validation.txt', 'r', encoding='utf-8') as file: # Changed encoding to 'utf-8'
    val_data = file.readlines()
train_data = [line.strip().split('|') for line in train_data]
val_data = [line.strip().split('|') for line in val_data]

In [4]:
import pandas as pd


# Create a data frame from the content of the .txt file
train_data = pd.DataFrame(train_data, columns=['Nom du fichier', 'Texte diacrité','Speaker_ID'])
val_data = pd.DataFrame(val_data, columns=['Nom du fichier', 'Texte diacrité','Speaker_ID'])

# Display the data frame
train_data.head(10)

,Nom du fichier,Texte diacrité,Speaker_ID
0,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,دَعْكَ مِنَ الأَسْئِلَةِ وَرَكِزْ فِيمَا أَقُولُ,0
1,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,لَوْلا أَنَّ أَهْلَكِ أَخْرِجُونِي مِنْكِ مَا ...,0
2,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,لَيْسُوا عَلَى دِينِكُمْ وَلا عَلَى دِينِنَا ف...,0
3,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,جَاءَنَا بِهِ رَسُولٌ مِنَّا,0
4,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,Sokran le kell ezt egy góga.,0
5,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,cfyg,5
6,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,I got that.,2
7,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,mmm,0
8,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,هَلْ تَظُنُّ ذَلِكَ حَقًّا؟,5
9,C:\Users\Ons Hadrich\Desktop\PFE\Tacotron2\tts...,سَيَتَّبِعُونَ مُحَمَّداً أَينَما ذَهَبَ,3

In [5]:
import text


#Helper function that turns arabic text into phonemes
def preprocess(txt):
  t_phon = text.arabic_to_buckwalter(txt)
  t_phon = text.buckwalter_to_phonemes(t_phon)
  return t_phon

In [6]:
train_phonemes,val_phonemes = [], []

for _, row in train_data.iterrows():
  row['Nom du fichier'] += ''
  train_phonemes.append(preprocess(row['Texte diacrité']))

for _,row in val_data.iterrows():
  row['Nom du fichier'] += ''
  val_phonemes.append(preprocess(row['Texte diacrité']))
train_data = train_data.assign(Phonemes=train_phonemes)
val_data = val_data.assign(Phonemes=val_phonemes)
train_data = train_data.drop('Texte diacrité', axis=1)
val_data = val_data.drop('Texte diacrité', axis=1)

In [7]:

import csv
train_data.to_csv('data\custom_data/ready_train.txt', sep=' ', header=None, index=None, quoting=csv.QUOTE_NONNUMERIC)
val_data.to_csv('data\custom_data/ready_val.txt', sep=' ', header=None, index=None, quoting=csv.QUOTE_NONNUMERIC)

In [8]:
# %%
import os
import torch
import librosa
import numpy as np
import torch.nn.functional as F
from tqdm import tqdm
import pandas as pd
from utils.audio import MelSpectrogram
from utils import write_lines_to_file

# %% CONFIG

csv_path = 'data\custom_data\MSATTS_updated.csv'
pitch_dict_path = 'data\custom_data/pitch_dict.pt'

# Load the dataset to determine which files to process
df = pd.read_csv(csv_path)
waves = df['Nom du fichier'].tolist()  # Get full paths from the CSV
print(f"{len(waves)} wave files found in {csv_path}")

mel_trf = MelSpectrogram()

# %% Load existing pitch dictionary if it exists
pitch_dict = {}
if os.path.exists(pitch_dict_path):
    try:
        pitch_dict = torch.load(pitch_dict_path)
        print(f"Loaded existing pitch dictionary with {len(pitch_dict)} entries.")
    except Exception as e:
        print(f"Error loading pitch dictionary: {e}. Starting with an empty dictionary.")
else:
    print("No existing pitch dictionary found. Starting fresh.")

# %% Extract pitch (f0) values

for i, wav_path in tqdm(enumerate(waves), total=len(waves)):
    wav_name = os.path.basename(wav_path)  # Extract filename for dictionary key

    # Skip if the file is already processed
    if wav_name in pitch_dict:
        continue

    try:
        # Check if file exists
        if not os.path.exists(wav_path):
            print(f"Warning: File not found: {wav_path}. Skipping.")
            continue

        # Load and process the audio
        wav, sr = librosa.load(wav_path, sr=mel_trf.sample_rate)
        mel_spec = mel_trf(torch.tensor(wav)[None])[0]  # [mel_bands, T]

        # Estimate pitch
        pitch_mel, voiced_flag, voiced_probs = librosa.pyin(
            wav, sr=mel_trf.sample_rate,
            fmin=librosa.note_to_hz('C2'),
            fmax=librosa.note_to_hz('C7'),
            frame_length=mel_trf.win_length,
            hop_length=mel_trf.hop_length)

        pitch_mel = np.where(np.isnan(pitch_mel), 0., pitch_mel)  # Set NaN to zero
        pitch_mel = torch.from_numpy(pitch_mel)
        pitch_mel = F.pad(pitch_mel, (0, mel_spec.size(1) - pitch_mel.size(0)))  # Pad to mel length

        # Store in dictionary using filename as key
        pitch_dict[wav_name] = pitch_mel

        # Save intermediate dict every 10 files
        if i % 10 == 0 and i > 0:
            torch.save(pitch_dict, pitch_dict_path)
            print(f"Intermediate save at {i} files: {len(pitch_dict)} entries.")

    except Exception as e:
        print(f"Error processing {wav_name}: {e}")
        continue

# Final save
torch.save(pitch_dict, pitch_dict_path)
print(f"Final pitch dictionary saved with {len(pitch_dict)} entries.")

2128 wave files found in data\custom_data\MSATTS_updated.csv
No existing pitch dictionary found. Starting fresh.

  1%|          | 11/2128 [01:01<2:09:07,  3.66s/it]

Intermediate save at 10 files: 11 entries.

  1%|          | 21/2128 [01:31<2:02:27,  3.49s/it]

Intermediate save at 20 files: 21 entries.

  1%|▏         | 31/2128 [01:58<1:24:00,  2.40s/it]

Intermediate save at 30 files: 31 entries.

  2%|▏         | 41/2128 [02:27<1:33:17,  2.68s/it]

Intermediate save at 40 files: 41 entries.

  2%|▏         | 51/2128 [02:55<2:02:55,  3.55s/it]

Intermediate save at 50 files: 51 entries.

  3%|▎         | 61/2128 [03:42<2:24:27,  4.19s/it]

Intermediate save at 60 files: 61 entries.

  3%|▎         | 71/2128 [04:17<2:20:48,  4.11s/it]

Intermediate save at 70 files: 71 entries.

  4%|▍         | 81/2128 [04:56<1:41:34,  2.98s/it]

Intermediate save at 80 files: 81 entries.

  4%|▍         | 91/2128 [05:22<1:45:01,  3.09s/it]

Intermediate save at 90 files: 91 entries.

  5%|▍         | 101/2128 [06:00<1:55:06,  3.41s/it]

Intermediate save at 100 files: 101 entries.

  5%|▌         | 111/2128 [06:40<1:56:16,  3.46s/it]

Intermediate save at 110 files: 111 entries.

  6%|▌         | 121/2128 [07:08<1:17:08,  2.31s/it]

Intermediate save at 120 files: 121 entries.

  6%|▌         | 131/2128 [07:40<2:16:12,  4.09s/it]

Intermediate save at 130 files: 131 entries.

  7%|▋         | 141/2128 [08:15<1:43:33,  3.13s/it]

Intermediate save at 140 files: 141 entries.

  7%|▋         | 151/2128 [08:39<1:26:01,  2.61s/it]

Intermediate save at 150 files: 151 entries.

  8%|▊         | 161/2128 [09:33<3:09:43,  5.79s/it]

Intermediate save at 160 files: 161 entries.

  8%|▊         | 171/2128 [10:08<1:40:41,  3.09s/it]

Intermediate save at 170 files: 171 entries.

  9%|▊         | 181/2128 [10:45<1:11:13,  2.20s/it]

Intermediate save at 180 files: 181 entries.

  9%|▉         | 191/2128 [11:15<1:41:29,  3.14s/it]

Intermediate save at 190 files: 191 entries.

  9%|▉         | 201/2128 [11:43<1:25:28,  2.66s/it]

Intermediate save at 200 files: 201 entries.

 10%|▉         | 211/2128 [12:14<2:18:33,  4.34s/it]

Intermediate save at 210 files: 211 entries.

 10%|█         | 221/2128 [12:43<1:27:37,  2.76s/it]

Intermediate save at 220 files: 221 entries.

 11%|█         | 231/2128 [13:19<1:31:21,  2.89s/it]

Intermediate save at 230 files: 231 entries.

 11%|█▏        | 241/2128 [13:55<1:25:39,  2.72s/it]

Intermediate save at 240 files: 241 entries.

 12%|█▏        | 251/2128 [14:33<2:20:32,  4.49s/it]

Intermediate save at 250 files: 251 entries.

 12%|█▏        | 261/2128 [15:02<1:28:28,  2.84s/it]

Intermediate save at 260 files: 261 entries.

 13%|█▎        | 271/2128 [15:21<56:41,  1.83s/it]

Intermediate save at 270 files: 271 entries.

 13%|█▎        | 281/2128 [15:37<48:23,  1.57s/it]

Intermediate save at 280 files: 281 entries.

 14%|█▎        | 291/2128 [15:56<49:55,  1.63s/it]

Intermediate save at 290 files: 291 entries.

 14%|█▍        | 301/2128 [16:23<1:32:01,  3.02s/it]

Intermediate save at 300 files: 301 entries.

 15%|█▍        | 311/2128 [17:02<2:07:03,  4.20s/it]

Intermediate save at 310 files: 311 entries.

 15%|█▌        | 321/2128 [17:24<1:10:55,  2.35s/it]

Intermediate save at 320 files: 321 entries.

 16%|█▌        | 331/2128 [17:47<54:06,  1.81s/it]

Intermediate save at 330 files: 331 entries.

 16%|█▌        | 341/2128 [18:11<1:10:06,  2.35s/it]

Intermediate save at 340 files: 341 entries.

 16%|█▋        | 351/2128 [18:34<1:07:26,  2.28s/it]

Intermediate save at 350 files: 351 entries.

 17%|█▋        | 361/2128 [16:11:08<694:20:06, 1414.60s/it]

Intermediate save at 360 files: 361 entries.

 17%|█▋        | 371/2128 [16:11:46<21:54:27, 44.89s/it]

Intermediate save at 370 files: 371 entries.

 18%|█▊        | 381/2128 [16:12:19<2:22:10,  4.88s/it]

Intermediate save at 380 files: 381 entries.

 18%|█▊        | 391/2128 [16:12:55<1:52:04,  3.87s/it]

Intermediate save at 390 files: 391 entries.

 19%|█▉        | 401/2128 [16:13:25<1:24:21,  2.93s/it]

Intermediate save at 400 files: 401 entries.

 19%|█▉        | 411/2128 [16:13:48<1:05:12,  2.28s/it]

Intermediate save at 410 files: 411 entries.

 20%|█▉        | 421/2128 [16:14:17<1:14:55,  2.63s/it]

Intermediate save at 420 files: 421 entries.

 20%|██        | 431/2128 [16:14:52<1:57:59,  4.17s/it]

Intermediate save at 430 files: 431 entries.

 21%|██        | 441/2128 [16:15:17<59:43,  2.12s/it]

Intermediate save at 440 files: 441 entries.

 21%|██        | 451/2128 [16:15:43<1:01:49,  2.21s/it]

Intermediate save at 450 files: 451 entries.

 22%|██▏       | 461/2128 [16:16:19<2:06:18,  4.55s/it]

Intermediate save at 460 files: 461 entries.

 22%|██▏       | 471/2128 [16:16:51<1:39:42,  3.61s/it]

Intermediate save at 470 files: 471 entries.

 23%|██▎       | 481/2128 [16:17:23<1:19:41,  2.90s/it]

Intermediate save at 480 files: 481 entries.

 23%|██▎       | 491/2128 [16:17:47<43:30,  1.59s/it]

Intermediate save at 490 files: 491 entries.

 24%|██▎       | 501/2128 [16:18:13<47:18,  1.74s/it]

Intermediate save at 500 files: 501 entries.

 24%|██▍       | 511/2128 [16:18:32<43:42,  1.62s/it]

Intermediate save at 510 files: 511 entries.

 24%|██▍       | 521/2128 [16:18:53<52:46,  1.97s/it]

Intermediate save at 520 files: 521 entries.

 25%|██▍       | 531/2128 [16:19:19<1:23:13,  3.13s/it]

Intermediate save at 530 files: 531 entries.

 25%|██▌       | 541/2128 [16:19:39<56:32,  2.14s/it]

Intermediate save at 540 files: 541 entries.

 26%|██▌       | 551/2128 [16:19:57<41:23,  1.58s/it]

Intermediate save at 550 files: 551 entries.

 26%|██▋       | 561/2128 [16:20:15<29:01,  1.11s/it]

Intermediate save at 560 files: 561 entries.

 27%|██▋       | 571/2128 [16:20:34<52:27,  2.02s/it]

Intermediate save at 570 files: 571 entries.

 27%|██▋       | 581/2128 [16:20:49<38:53,  1.51s/it]

Intermediate save at 580 files: 581 entries.

 28%|██▊       | 591/2128 [16:21:07<48:56,  1.91s/it]

Intermediate save at 590 files: 591 entries.

 28%|██▊       | 601/2128 [16:21:33<57:34,  2.26s/it]

Intermediate save at 600 files: 601 entries.

 29%|██▊       | 611/2128 [16:21:52<57:10,  2.26s/it]

Intermediate save at 610 files: 611 entries.

 29%|██▉       | 621/2128 [16:22:20<44:51,  1.79s/it]

Intermediate save at 620 files: 621 entries.

 30%|██▉       | 631/2128 [16:22:42<1:00:23,  2.42s/it]

Intermediate save at 630 files: 631 entries.

 30%|███       | 641/2128 [16:23:12<51:17,  2.07s/it]

Intermediate save at 640 files: 641 entries.

 31%|███       | 651/2128 [16:23:39<1:07:32,  2.74s/it]

Intermediate save at 650 files: 651 entries.

 31%|███       | 661/2128 [16:24:01<57:15,  2.34s/it]

Intermediate save at 660 files: 661 entries.

 32%|███▏      | 671/2128 [16:24:27<52:50,  2.18s/it]

Intermediate save at 670 files: 671 entries.

 32%|███▏      | 681/2128 [16:25:00<1:08:16,  2.83s/it]

Intermediate save at 680 files: 681 entries.

 32%|███▏      | 691/2128 [16:25:45<3:07:00,  7.81s/it]

Intermediate save at 690 files: 691 entries.

 33%|███▎      | 701/2128 [16:26:08<1:20:02,  3.37s/it]

Intermediate save at 700 files: 701 entries.

 33%|███▎      | 711/2128 [16:26:23<55:16,  2.34s/it]

Intermediate save at 710 files: 711 entries.

 34%|███▍      | 721/2128 [16:26:58<1:08:22,  2.92s/it]

Intermediate save at 720 files: 721 entries.

 34%|███▍      | 731/2128 [16:27:45<2:31:09,  6.49s/it]

Intermediate save at 730 files: 731 entries.

 35%|███▍      | 741/2128 [16:28:03<37:43,  1.63s/it]

Intermediate save at 740 files: 741 entries.

 35%|███▌      | 751/2128 [16:28:24<47:39,  2.08s/it]

Intermediate save at 750 files: 751 entries.

 36%|███▌      | 761/2128 [16:28:51<47:29,  2.08s/it]

Intermediate save at 760 files: 761 entries.

 36%|███▌      | 771/2128 [16:29:07<46:25,  2.05s/it]

Intermediate save at 770 files: 771 entries.

 37%|███▋      | 781/2128 [16:29:30<1:11:26,  3.18s/it]

Intermediate save at 780 files: 781 entries.

 37%|███▋      | 791/2128 [16:30:05<1:32:16,  4.14s/it]

Intermediate save at 790 files: 791 entries.

 38%|███▊      | 801/2128 [16:30:24<43:37,  1.97s/it]

Intermediate save at 800 files: 801 entries.

 38%|███▊      | 811/2128 [16:30:54<1:01:47,  2.82s/it]

Intermediate save at 810 files: 811 entries.

 39%|███▊      | 821/2128 [16:31:25<1:34:33,  4.34s/it]

Intermediate save at 820 files: 821 entries.

 39%|███▉      | 831/2128 [16:31:50<54:42,  2.53s/it]

Intermediate save at 830 files: 831 entries.

 40%|███▉      | 841/2128 [16:32:23<1:23:08,  3.88s/it]

Intermediate save at 840 files: 841 entries.

 40%|███▉      | 851/2128 [16:33:02<1:49:14,  5.13s/it]

Intermediate save at 850 files: 851 entries.

 40%|████      | 861/2128 [16:33:28<56:28,  2.67s/it]

Intermediate save at 860 files: 861 entries.

 41%|████      | 871/2128 [16:33:57<1:07:26,  3.22s/it]

Intermediate save at 870 files: 871 entries.

 41%|████▏     | 881/2128 [16:34:32<1:26:01,  4.14s/it]

Intermediate save at 880 files: 881 entries.

 42%|████▏     | 891/2128 [16:35:04<1:07:01,  3.25s/it]

Intermediate save at 890 files: 891 entries.

 42%|████▏     | 901/2128 [16:35:37<1:34:17,  4.61s/it]

Intermediate save at 900 files: 901 entries.

 43%|████▎     | 911/2128 [16:36:06<1:01:30,  3.03s/it]

Intermediate save at 910 files: 911 entries.

 43%|████▎     | 921/2128 [16:36:39<1:04:44,  3.22s/it]

Intermediate save at 920 files: 921 entries.

 44%|████▍     | 931/2128 [16:37:12<59:22,  2.98s/it]

Intermediate save at 930 files: 931 entries.

 44%|████▍     | 941/2128 [16:38:03<2:12:18,  6.69s/it]

Intermediate save at 940 files: 941 entries.

 45%|████▍     | 951/2128 [16:38:45<2:00:07,  6.12s/it]

Intermediate save at 950 files: 951 entries.

 45%|████▌     | 961/2128 [16:39:04<37:46,  1.94s/it]

Intermediate save at 960 files: 961 entries.

 46%|████▌     | 971/2128 [16:39:27<43:08,  2.24s/it]

Intermediate save at 970 files: 971 entries.

 46%|████▌     | 981/2128 [16:39:51<47:54,  2.51s/it]

Intermediate save at 980 files: 981 entries.

 47%|████▋     | 991/2128 [16:40:05<30:53,  1.63s/it]

Intermediate save at 990 files: 991 entries.

 47%|████▋     | 1001/2128 [16:40:34<1:13:53,  3.93s/it]

Intermediate save at 1000 files: 1001 entries.

 48%|████▊     | 1011/2128 [16:40:58<1:04:11,  3.45s/it]

Intermediate save at 1010 files: 1011 entries.

 48%|████▊     | 1021/2128 [16:41:33<58:11,  3.15s/it]

Intermediate save at 1020 files: 1021 entries.

 48%|████▊     | 1031/2128 [16:41:56<40:27,  2.21s/it]

Intermediate save at 1030 files: 1031 entries.

 49%|████▉     | 1041/2128 [16:42:17<38:18,  2.11s/it]

Intermediate save at 1040 files: 1041 entries.

 49%|████▉     | 1051/2128 [16:42:41<42:54,  2.39s/it]

Intermediate save at 1050 files: 1051 entries.

 50%|████▉     | 1061/2128 [16:43:07<57:10,  3.21s/it]

Intermediate save at 1060 files: 1061 entries.

 50%|█████     | 1071/2128 [16:43:26<33:11,  1.88s/it]

Intermediate save at 1070 files: 1071 entries.

 51%|█████     | 1081/2128 [16:43:42<28:25,  1.63s/it]

Intermediate save at 1080 files: 1081 entries.

 51%|█████▏    | 1091/2128 [16:43:58<33:47,  1.95s/it]

Intermediate save at 1090 files: 1091 entries.

 52%|█████▏    | 1101/2128 [16:44:21<45:03,  2.63s/it]

Intermediate save at 1100 files: 1101 entries.

 52%|█████▏    | 1111/2128 [16:44:43<36:49,  2.17s/it]

Intermediate save at 1110 files: 1111 entries.

 53%|█████▎    | 1121/2128 [16:45:06<31:54,  1.90s/it]

Intermediate save at 1120 files: 1121 entries.

 53%|█████▎    | 1131/2128 [16:45:33<52:29,  3.16s/it]

Intermediate save at 1130 files: 1131 entries.

 54%|█████▎    | 1141/2128 [16:46:03<27:39,  1.68s/it]

Intermediate save at 1140 files: 1141 entries.

 54%|█████▍    | 1151/2128 [16:46:22<30:25,  1.87s/it]

Intermediate save at 1150 files: 1151 entries.

 55%|█████▍    | 1161/2128 [16:46:48<42:05,  2.61s/it]

Intermediate save at 1160 files: 1161 entries.

 55%|█████▌    | 1171/2128 [16:47:10<45:03,  2.82s/it]

Intermediate save at 1170 files: 1171 entries.

 55%|█████▌    | 1181/2128 [16:47:41<48:58,  3.10s/it]

Intermediate save at 1180 files: 1181 entries.

 56%|█████▌    | 1191/2128 [16:47:59<24:32,  1.57s/it]

Intermediate save at 1190 files: 1191 entries.

 56%|█████▋    | 1201/2128 [16:48:22<34:08,  2.21s/it]

Intermediate save at 1200 files: 1201 entries.

 57%|█████▋    | 1211/2128 [16:48:43<30:20,  1.99s/it]

Intermediate save at 1210 files: 1211 entries.

 57%|█████▋    | 1221/2128 [16:49:00<15:42,  1.04s/it]

Intermediate save at 1220 files: 1221 entries.

 58%|█████▊    | 1231/2128 [16:49:36<51:10,  3.42s/it]

Intermediate save at 1230 files: 1231 entries.

 58%|█████▊    | 1241/2128 [16:50:07<46:42,  3.16s/it]

Intermediate save at 1240 files: 1241 entries.

 59%|█████▉    | 1251/2128 [16:50:26<21:40,  1.48s/it]

Intermediate save at 1250 files: 1251 entries.

 59%|█████▉    | 1261/2128 [16:50:49<48:05,  3.33s/it]

Intermediate save at 1260 files: 1261 entries.

 60%|█████▉    | 1271/2128 [16:51:29<47:38,  3.34s/it]

Intermediate save at 1270 files: 1271 entries.

 60%|██████    | 1281/2128 [16:51:50<27:21,  1.94s/it]

Intermediate save at 1280 files: 1281 entries.

 61%|██████    | 1291/2128 [16:52:26<45:32,  3.27s/it]

Intermediate save at 1290 files: 1291 entries.

 61%|██████    | 1301/2128 [16:52:54<43:23,  3.15s/it]

Intermediate save at 1300 files: 1301 entries.

 62%|██████▏   | 1311/2128 [16:53:20<35:21,  2.60s/it]

Intermediate save at 1310 files: 1311 entries.

 62%|██████▏   | 1321/2128 [16:53:50<45:09,  3.36s/it]

Intermediate save at 1320 files: 1321 entries.

 63%|██████▎   | 1331/2128 [16:54:23<36:55,  2.78s/it]

Intermediate save at 1330 files: 1331 entries.

 63%|██████▎   | 1341/2128 [16:54:52<31:22,  2.39s/it]

Intermediate save at 1340 files: 1341 entries.

 63%|██████▎   | 1351/2128 [16:55:17<30:59,  2.39s/it]

Intermediate save at 1350 files: 1351 entries.

 64%|██████▍   | 1361/2128 [16:55:48<42:16,  3.31s/it]

Intermediate save at 1360 files: 1361 entries.

 64%|██████▍   | 1371/2128 [16:56:09<26:44,  2.12s/it]

Intermediate save at 1370 files: 1371 entries.

 65%|██████▍   | 1381/2128 [16:56:32<31:17,  2.51s/it]

Intermediate save at 1380 files: 1381 entries.

 65%|██████▌   | 1391/2128 [16:56:55<24:31,  2.00s/it]

Intermediate save at 1390 files: 1391 entries.

 66%|██████▌   | 1401/2128 [16:57:16<27:57,  2.31s/it]

Intermediate save at 1400 files: 1401 entries.

 66%|██████▋   | 1411/2128 [16:57:41<34:31,  2.89s/it]

Intermediate save at 1410 files: 1411 entries.

 67%|██████▋   | 1421/2128 [16:58:03<26:16,  2.23s/it]

Intermediate save at 1420 files: 1421 entries.

 67%|██████▋   | 1431/2128 [16:58:30<34:39,  2.98s/it]

Intermediate save at 1430 files: 1431 entries.

 68%|██████▊   | 1441/2128 [16:59:00<33:31,  2.93s/it]

Intermediate save at 1440 files: 1441 entries.

 68%|██████▊   | 1451/2128 [16:59:41<56:48,  5.04s/it]

Intermediate save at 1450 files: 1451 entries.

 69%|██████▊   | 1461/2128 [17:00:13<30:03,  2.70s/it]

Intermediate save at 1460 files: 1461 entries.

 69%|██████▉   | 1471/2128 [17:00:50<43:28,  3.97s/it]

Intermediate save at 1470 files: 1471 entries.

 70%|██████▉   | 1481/2128 [17:01:35<49:14,  4.57s/it]

Intermediate save at 1480 files: 1481 entries.

 70%|███████   | 1491/2128 [17:02:05<29:33,  2.78s/it]

Intermediate save at 1490 files: 1491 entries.

 71%|███████   | 1501/2128 [17:02:30<25:02,  2.40s/it]

Intermediate save at 1500 files: 1501 entries.

 71%|███████   | 1511/2128 [17:03:00<28:49,  2.80s/it]

Intermediate save at 1510 files: 1511 entries.

 71%|███████▏  | 1521/2128 [17:03:29<28:50,  2.85s/it]

Intermediate save at 1520 files: 1521 entries.

 72%|███████▏  | 1531/2128 [17:04:00<33:11,  3.34s/it]

Intermediate save at 1530 files: 1531 entries.

 72%|███████▏  | 1541/2128 [17:04:25<18:42,  1.91s/it]

Intermediate save at 1540 files: 1541 entries.

 73%|███████▎  | 1551/2128 [17:04:48<25:57,  2.70s/it]

Intermediate save at 1550 files: 1551 entries.

 73%|███████▎  | 1561/2128 [17:05:22<31:38,  3.35s/it]

Intermediate save at 1560 files: 1561 entries.

 74%|███████▍  | 1571/2128 [17:05:47<23:27,  2.53s/it]

Intermediate save at 1570 files: 1571 entries.

 74%|███████▍  | 1581/2128 [17:06:18<31:45,  3.48s/it]

Intermediate save at 1580 files: 1581 entries.

 75%|███████▍  | 1591/2128 [17:06:53<27:56,  3.12s/it]

Intermediate save at 1590 files: 1591 entries.

 75%|███████▌  | 1601/2128 [17:07:18<21:17,  2.42s/it]

Intermediate save at 1600 files: 1601 entries.

 76%|███████▌  | 1611/2128 [17:07:55<37:47,  4.39s/it]

Intermediate save at 1610 files: 1611 entries.

 76%|███████▌  | 1621/2128 [17:08:26<23:22,  2.77s/it]

Intermediate save at 1620 files: 1621 entries.

 77%|███████▋  | 1631/2128 [17:08:53<24:27,  2.95s/it]

Intermediate save at 1630 files: 1631 entries.

 77%|███████▋  | 1641/2128 [17:09:34<33:19,  4.11s/it]

Intermediate save at 1640 files: 1641 entries.

 78%|███████▊  | 1651/2128 [17:10:19<24:53,  3.13s/it]

Intermediate save at 1650 files: 1651 entries.

 78%|███████▊  | 1661/2128 [17:10:45<23:15,  2.99s/it]

Intermediate save at 1660 files: 1661 entries.

 79%|███████▊  | 1671/2128 [17:11:11<20:35,  2.70s/it]

Intermediate save at 1670 files: 1671 entries.

 79%|███████▉  | 1681/2128 [17:11:37<15:43,  2.11s/it]

Intermediate save at 1680 files: 1681 entries.

 79%|███████▉  | 1691/2128 [17:12:06<16:05,  2.21s/it]

Intermediate save at 1690 files: 1691 entries.

 80%|███████▉  | 1701/2128 [17:12:26<15:49,  2.22s/it]

Intermediate save at 1700 files: 1701 entries.

 80%|████████  | 1711/2128 [17:12:55<19:29,  2.80s/it]

Intermediate save at 1710 files: 1711 entries.

 81%|████████  | 1721/2128 [17:13:27<29:36,  4.36s/it]

Intermediate save at 1720 files: 1721 entries.

 81%|████████▏ | 1731/2128 [17:13:57<18:23,  2.78s/it]

Intermediate save at 1730 files: 1731 entries.

 82%|████████▏ | 1741/2128 [17:14:25<16:43,  2.59s/it]

Intermediate save at 1740 files: 1741 entries.

 82%|████████▏ | 1751/2128 [17:14:46<14:32,  2.31s/it]

Intermediate save at 1750 files: 1751 entries.

 83%|████████▎ | 1761/2128 [17:15:09<15:31,  2.54s/it]

Intermediate save at 1760 files: 1761 entries.

 83%|████████▎ | 1771/2128 [17:15:33<12:10,  2.05s/it]

Intermediate save at 1770 files: 1771 entries.

 84%|████████▎ | 1781/2128 [17:16:07<22:41,  3.92s/it]

Intermediate save at 1780 files: 1781 entries.

 84%|████████▍ | 1791/2128 [17:16:41<19:38,  3.50s/it]

Intermediate save at 1790 files: 1791 entries.

 85%|████████▍ | 1801/2128 [17:17:22<22:14,  4.08s/it]

Intermediate save at 1800 files: 1801 entries.

 85%|████████▌ | 1811/2128 [17:17:58<24:14,  4.59s/it]

Intermediate save at 1810 files: 1811 entries.

 86%|████████▌ | 1821/2128 [17:18:51<27:18,  5.34s/it]

Intermediate save at 1820 files: 1821 entries.

 86%|████████▌ | 1831/2128 [17:19:15<08:26,  1.70s/it]

Intermediate save at 1830 files: 1831 entries.

 87%|████████▋ | 1841/2128 [17:19:44<17:24,  3.64s/it]

Intermediate save at 1840 files: 1841 entries.

 87%|████████▋ | 1851/2128 [17:20:08<10:43,  2.32s/it]

Intermediate save at 1850 files: 1851 entries.

 87%|████████▋ | 1861/2128 [17:20:44<15:33,  3.49s/it]

Intermediate save at 1860 files: 1861 entries.

 88%|████████▊ | 1871/2128 [17:21:11<09:38,  2.25s/it]

Intermediate save at 1870 files: 1871 entries.

 88%|████████▊ | 1881/2128 [17:21:48<10:20,  2.51s/it]

Intermediate save at 1880 files: 1881 entries.

 89%|████████▉ | 1891/2128 [17:22:28<24:09,  6.12s/it]

Intermediate save at 1890 files: 1891 entries.

 89%|████████▉ | 1901/2128 [17:23:11<28:09,  7.44s/it]

Intermediate save at 1900 files: 1901 entries.

 90%|████████▉ | 1911/2128 [17:23:35<07:16,  2.01s/it]

Intermediate save at 1910 files: 1911 entries.

 90%|█████████ | 1921/2128 [17:24:14<14:46,  4.28s/it]

Intermediate save at 1920 files: 1921 entries.

 91%|█████████ | 1931/2128 [17:25:04<17:33,  5.35s/it]

Intermediate save at 1930 files: 1931 entries.

 91%|█████████ | 1941/2128 [17:25:46<16:28,  5.29s/it]

Intermediate save at 1940 files: 1941 entries.

 92%|█████████▏| 1951/2128 [17:26:13<07:41,  2.61s/it]

Intermediate save at 1950 files: 1951 entries.

 92%|█████████▏| 1961/2128 [17:26:56<11:59,  4.31s/it]

Intermediate save at 1960 files: 1961 entries.

 93%|█████████▎| 1971/2128 [17:27:17<06:06,  2.33s/it]

Intermediate save at 1970 files: 1971 entries.

 93%|█████████▎| 1981/2128 [17:27:34<03:50,  1.57s/it]

Intermediate save at 1980 files: 1981 entries.

 94%|█████████▎| 1991/2128 [17:28:03<06:09,  2.70s/it]

Intermediate save at 1990 files: 1991 entries.

 94%|█████████▍| 2001/2128 [17:28:37<06:50,  3.23s/it]

Intermediate save at 2000 files: 2001 entries.

 95%|█████████▍| 2011/2128 [17:29:04<06:26,  3.31s/it]

Intermediate save at 2010 files: 2011 entries.

 95%|█████████▍| 2021/2128 [17:29:31<04:54,  2.75s/it]

Intermediate save at 2020 files: 2021 entries.

 95%|█████████▌| 2031/2128 [17:29:56<03:38,  2.25s/it]

Intermediate save at 2030 files: 2031 entries.

 96%|█████████▌| 2041/2128 [17:30:31<07:05,  4.89s/it]

Intermediate save at 2040 files: 2041 entries.

 96%|█████████▋| 2051/2128 [17:31:01<03:51,  3.01s/it]

Intermediate save at 2050 files: 2051 entries.

 97%|█████████▋| 2061/2128 [17:31:45<06:04,  5.44s/it]

Intermediate save at 2060 files: 2061 entries.

 97%|█████████▋| 2071/2128 [17:32:11<02:57,  3.11s/it]

Intermediate save at 2070 files: 2071 entries.

 98%|█████████▊| 2081/2128 [17:33:03<04:24,  5.62s/it]

Intermediate save at 2080 files: 2081 entries.

 98%|█████████▊| 2091/2128 [17:33:52<03:15,  5.28s/it]

Intermediate save at 2090 files: 2091 entries.

 99%|█████████▊| 2101/2128 [17:35:13<05:24, 12.03s/it]

Intermediate save at 2100 files: 2101 entries.

 99%|█████████▉| 2111/2128 [17:36:02<01:11,  4.19s/it]

Intermediate save at 2110 files: 2111 entries.

100%|█████████▉| 2121/2128 [17:36:52<00:27,  3.90s/it]

Intermediate save at 2120 files: 2121 entries.

100%|██████████| 2128/2128 [17:37:11<00:00, 29.81s/it]

Final pitch dictionary saved with 2128 entries.

In [18]:
# %% Calculate pitch mean and std

rmean = 0
rvar = 0
ndata = 0

for pitch_mel in pitch_dict.values():
    pitch_mel = np.where(np.isnan(pitch_mel), 0.0, pitch_mel)

    pitch_mel_ = pitch_mel[pitch_mel > 1]
    if len(pitch_mel_) == 0:  # Skip if no valid pitch values
        continue

    p_mean = np.mean(pitch_mel_)
    p_var = np.var(pitch_mel_)
    p_len = len(pitch_mel_)

    rvar = ((ndata-1)*rvar + (p_len-1)*p_var) / (ndata + p_len - 1) + \
            ndata*p_len*(p_mean - rmean)**2 / ((ndata + p_len)*(ndata + p_len - 1))

    rmean = (p_len*p_mean + ndata*rmean) / (p_len + ndata)

    ndata += p_len

mean, std = rmean, np.sqrt(rvar)
print('Mean:', mean)
print('Std:', std)

write_lines_to_file(path='/content/drive/MyDrive/Stage_pfe/models_tts/mean_std.txt',
                    lines=[f"mean: {mean}",
                           f"std: {std}"])

Mean: 292.7427337939664
Std: 163.88325955359096